# Generated by Django 5.2.5 on 2025-08-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_acc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
