# Generated by Django 5.2.5 on 2025-08-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olcha", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
