# Generated by Django 5.2.5 on 2025-08-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olcha", "0004_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="product/images/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
