# Generated by Django 5.2.5 on 2025-08-29 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olcha", "0005_product_image_alter_product_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="desc",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="title",
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(default="Default name", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="olcha.category",
            ),
        ),
    ]
