# Generated by Django 5.2.5 on 2025-08-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olcha", "0007_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
